@BASE_URL=http://localhost:3001

### 회원가입 테스트
POST {{BASE_URL}}/users
Content-Type:application/json

{
  "email":"rat@rat.com",
  "name":"minsu",
  "password":"ratratrat"
}

### 로그인 테스트
POST {{BASE_URL}}/users/login
Content-Type:application/json

{
  "email":"rat@rat.com",
  "password":"ratratrat"
}

### 상품 생성 테스트
POST {{BASE_URL}}/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc4MzA0MTg1OSwiZXhwIjoxNzgzMDQ1NDU5fQ.035cQQGRWxuNk_8L6A38yxujyfW7yANPJllE21vLEhw

{
  "price":20000,
  "name":"상품이름1",
  "description":"상품소개1"
}

# ### 상품 등록 테스트 (이미지 2개)
# POST {{BASE_URL}}/products
# Content-Type: multipart/form-data; boundary=----boundary
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc4MzA1NTA5MywiZXhwIjoxNzgzMDU4NjkzfQ.-ZtzJ-hpRB6ckQzwQRm_Rb0qJr2FbRxgBZZzhUd25Zg

# ------boundary
# Content-Disposition: form-data; name="name"

# 상품이름3
# ------boundary
# Content-Disposition: form-data; name="description"

# 상품소개3
# ------boundary
# Content-Disposition: form-data; name="price"

# 33333
# ------boundary
# Content-Disposition: form-data; name="images"; filename="a.jpg"
# Content-Type: image/jpeg
# ------boundary--

# < ./test-assets/a.jpg
# ------boundary
# Content-Disposition: form-data; name="images"; filename="b.jpg"
# Content-Type: image/jpeg

# < ./test-assets/b.jpg
# ------boundary--

###
### 상품 등록 테스트 (이미지 2개)
POST {{BASE_URL}}/products
Content-Type: multipart/form-data; boundary=----boundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc4MzA2NDM1MSwiZXhwIjoxNzgzMDY3OTUxfQ.KZ42KGwwUnbI6eIKJshY2-ZU5EC19W98KVNt3-MpBto

------boundary
Content-Disposition: form-data; name="name"

상품이름6
------boundary
Content-Disposition: form-data; name="description"

상품소개6
------boundary
Content-Disposition: form-data; name="price"

66666
------boundary
Content-Disposition: form-data; name="images"; filename="a.jpg"
Content-Type: image/jpeg

< ./test-assets/a.jpg
------boundary
Content-Disposition: form-data; name="images"; filename="b.jpg"
Content-Type: image/jpeg

< ./test-assets/b.jpg
------boundary
Content-Disposition: form-data; name="tags"

중고
------boundary
Content-Disposition: form-data; name="tags"

인기
------boundary
Content-Disposition: form-data; name="tags"

신규
------boundary
Content-Disposition: form-data; name="tags"

중고
------boundary
Content-Disposition: form-data; name="tags"

중고
------boundary
Content-Disposition: form-data; name="tags"

중고
------boundary--