###전체 상품 조회
@baseUrl=http://localhost:3000

GET {{baseUrl}}/products?keyword=지갑

###상세 상품 조회
GET {{baseUrl}}/products/69fc1654dd4742b17fb9d5c4

### 상품 추가
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name":"뭘보노",
  "description":"뭐요",
  "price":100,
  "tags":["아아","으아아"]
}

###상품업데이트
PATCH {{baseUrl}}/products/69fc1654dd4742b17fb9d5c4
Content-Type: application/json

{
  "name":"이름 업데이또"
}

###상품삭제
DELETE {{baseUrl}}/products/69fc0f7fa06654e87cc546c4